config/routes.rb
Rails.application.routes.draw do
  resources :marks
  resources :servicos
  devise_for :users
  root to: 'home#index' 
  resources :agendamentos
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/agendamento.rb
class Agendamento < ActiveRecord::Base
    validates :data, uniqueness: true
end

app/models/mark.rb
class Mark < ActiveRecord::Base
  validates :data, uniqueness: true
  belongs_to :servico
  def servico_nome
    servico.nome if servico
  end
end

app/models/servico.rb
class Servico < ActiveRecord::Base
    has_many :marks
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/agendamentos_controller.rb
class AgendamentosController < ApplicationController
  before_action :set_agendamento, only: [:show, :edit, :update, :destroy]
  # GET /agendamentos
  # GET /agendamentos.json
  def index
    @agendamentos = Agendamento.all
  end

  # GET /agendamentos/1
  # GET /agendamentos/1.json
  def show
  end

  # GET /agendamentos/new
  def new
    @agendamento = Agendamento.new
  end

  # GET /agendamentos/1/edit
  def edit
  end

  # POST /agendamentos
  # POST /agendamentos.json
  def create
    @agendamento = Agendamento.new(agendamento_params)
    
    respond_to do |format|
      if @agendamento.save
        format.html { redirect_to @agendamento, notice: 'Agendamento feito com sucesso!' }
        format.json { render :show, status: :created, location: @agendamento }
      else
        format.html { render :new }
        format.json { render json: @agendamento.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /agendamentos/1
  # PATCH/PUT /agendamentos/1.json
  def update
    respond_to do |format|
      if @agendamento.update(agendamento_params)
        format.html { redirect_to @agendamento, notice: 'Agendamento alterado com sucesso!' }
        format.json { render :show, status: :ok, location: @agendamento }
      else
        format.html { render :edit }
        format.json { render json: @agendamento.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /agendamentos/1
  # DELETE /agendamentos/1.json
  def destroy
    @agendamento.destroy
    respond_to do |format|
      format.html { redirect_to agendamentos_url, notice: 'Agendamento cancelado' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_agendamento
      @agendamento = Agendamento.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def agendamento_params
      params.require(:agendamento).permit(:data, :cliente, :servico)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    def index
       #render text: "Seja Bem-vindo!"
       @message = 'Seja Bem-vindo!'
    end
    before_action :authenticate_user!
end

app/controllers/marks_controller.rb
class MarksController < InheritedResources::Base

  private

    def mark_params
      params.require(:mark).permit(:name, :data, :servico_id)
    end
end

app/controllers/servicos_controller.rb
class ServicosController < InheritedResources::Base
before_action :authenticate_admin_user!
  private

    def servico_params
      params.require(:servico).permit(:nome)
    end
end

app/helpers/agendamentos_helper.rb
module AgendamentosHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/marks_helper.rb
module MarksHelper
end

app/helpers/servicos_helper.rb
module ServicosHelper
end

app/views/agendamentos/_form.html.erb
<%= form_for(@agendamento) do |f| %>
  <% if @agendamento.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@agendamento.errors.count, "error") %> prohibited this agendamento from being saved:</h2>

      <ul>
      <% @agendamento.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :data %><br>
    <%= f.datetime_select :data %>
  </div>
  <div class="field">
    <%= f.label :cliente %><br>
    <%= f.text_field :cliente %>
  </div>
  <div class="field">
    <%= f.label :servico %><br>
    <%= f.text_field :servico %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/agendamentos/edit.html.erb
<h1>Editing Agendamento</h1>

<%= render 'form' %>

<%= link_to 'Show', @agendamento %> |
<%= link_to 'Back', agendamentos_path %>

app/views/agendamentos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Serviços Agendados</h1>

<table>
  <thead>
    <tr>
      <th>Data</th>
      <th>Cliente</th>
      <th>Servico</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @agendamentos.each do |agendamento| %>
      <tr>
        <td><%= agendamento.data %></td>
        <td><%= agendamento.cliente %></td>
        <td><%= agendamento.servico %></td>
        <td><%= link_to 'Mostrar', agendamento %></td>
        <td><%= link_to 'Editar Agendamento', edit_agendamento_path(agendamento) %></td>
        <td><%= link_to 'Cancelar Agendamento', agendamento, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Agendar novo Serviço', new_agendamento_path %>

app/views/agendamentos/new.html.erb
<h1>New Agendamento</h1>

<%= render 'form' %>

<%= link_to 'Back', agendamentos_path %>

app/views/agendamentos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Data:</strong>
  <%= @agendamento.data %>
</p>

<p>
  <strong>Cliente:</strong>
  <%= @agendamento.cliente %>
</p>

<p>
  <strong>Servico:</strong>
  <%= @agendamento.servico %>
</p>

<%= link_to 'Edit', edit_agendamento_path(@agendamento) %> |
<%= link_to 'Back', agendamentos_path %>

app/views/home/index.html.erb
<html>
  <body>
     <h1><%= @message %></h1>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.0.3/css/bootstrap.css">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.0.3/css/bootstrap-theme.css">
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>

<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">Inicio</a>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <li><a href="/marks">Agendamentos</a></li>
      </ul>
      <ul class="nav navbar-nav">
        <li><a href="/admin">Administradores</a></li>
      </ul>
    </div>
  </div>
</nav>

<p class="navbar-text fixed-top pull-right">
<% if user_signed_in? %>
  Bem-vindo, <strong><%= current_user.email %></strong>.
  <%= link_to 'Configurar Perfil', edit_user_registration_path, :class => 'navbar-link' %> |
  <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
<% else %>
  <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
  <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
<% end %>
</p>

<body>

<div class="container">
  <%= yield %>
</div>


<% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>

</body>

<footer>
  <div class="container">
    Desafio-Ctic <%= Time.now.year %>
  </div>
</footer>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.0.3/js/bootstrap.js"></script>

</html>

app/views/marks/_form.html.erb
<%= form_for(@mark) do |f| %>
  <% if @mark.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@mark.errors.count, "error") %> prohibited this mark from being saved:</h2>

      <ul>
      <% @mark.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :data %><br>
    <%= f.datetime_select :data %>
  </div>
  <div class="field">
    <%= f.label :servico_id %><br>
    <%= f.collection_select(:servico_id,
                            Servico.all,
                            :id,
                            :nome,
                           { :prompt => true })
 %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/marks/edit.html.erb
<h1>Editing Mark</h1>

<%= render 'form' %>

<%= link_to 'Mostrar', @mark %> |
<%= link_to 'Back', marks_path %>

app/views/marks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Serviços Agendados</h1>

<table>
  <thead>
    <tr>
      <th>Cliente</th>
      <th>Data</th>
      <th>Serviço</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @marks.each do |mark| %>
      <tr>
        <td><%= mark.name %></td>
        <td><%= mark.data %></td>
        <td><%= mark.servico_nome %></td>
        <td><%= link_to 'Mostrar', mark %></td>
        <td><%= link_to 'Editar', edit_mark_path(mark) %></td>
        <td><%= link_to 'Cancelar Agendamento', mark, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Novo agendamento', new_mark_path %>

app/views/marks/new.html.erb
<h1>Novo agendamento</h1>

<%= render 'form' %>

<%= link_to 'Back', marks_path %>

app/views/marks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Cliente:</strong>
  <%= @mark.name %>
</p>

<p>
  <strong>Data:</strong>
  <%= @mark.data %>
</p>

<p>
  <strong>Serviço:</strong>
  <%= @mark.servico_nome %>
</p>

<%= link_to 'Editar', edit_mark_path(@mark) %> |
<%= link_to 'Back', marks_path %>

app/views/servicos/_form.html.erb
<%= form_for(@servico) do |f| %>
  <% if @servico.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@servico.errors.count, "error") %> prohibited this servico from being saved:</h2>

      <ul>
      <% @servico.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nome %><br>
    <%= f.text_field :nome %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/servicos/edit.html.erb
<h1>Editing Servico</h1>

<%= render 'form' %>

<%= link_to 'Show', @servico %> |
<%= link_to 'Back', servicos_path %>

app/views/servicos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Servicos</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @servicos.each do |servico| %>
      <tr>
        <td><%= servico.nome %></td>
        <td><%= link_to 'Show', servico %></td>
        <td><%= link_to 'Edit', edit_servico_path(servico) %></td>
        <td><%= link_to 'Destroy', servico, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Servico', new_servico_path %>

app/views/servicos/new.html.erb
<h1>New Servico</h1>

<%= render 'form' %>

<%= link_to 'Back', servicos_path %>

app/views/servicos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @servico.nome %>
</p>

<%= link_to 'Edit', edit_servico_path(@servico) %> |
<%= link_to 'Back', servicos_path %>